"""smaa_embed.py - makes src/smaa/smaa.h from a checkout of https://github.com/iryoku/smaa (MIT).

    python tools/smaa_embed.py <smaa checkout> src/smaa/smaa.h

The header holds SMAA.hlsl without its comments as one C string (compiled as GLSL 1.30 with SMAA_GLSL_3 by src/postfx.c)
and the two lookup textures as PNG files (AreaTex 160x560 RG = PNG grey+alpha, SearchTex 64x16 R = PNG grey), decoded
with stb_image at run time: about 170 KB of source instead of the 1.2 MB of AreaTex.h."""
import io, re, sys
from PIL import Image

src, out = sys.argv[1], sys.argv[2]

def read(p): return open(p, encoding='latin-1').read().replace('\r\n', '\n')

def tex_bytes(path, name):
    t = read(path)
    w = int(re.search(r'#define %s_WIDTH (\d+)' % name, t).group(1)); h = int(re.search(r'#define %s_HEIGHT (\d+)' % name, t).group(1))
    body = t[t.index('{', t.index('Bytes[]')) + 1:t.index('}', t.index('Bytes[]'))]
    return w, h, bytes(int(x, 16) for x in re.findall(r'0x[0-9a-fA-F]{2}', body))

def png(img):
    b = io.BytesIO(); img.save(b, 'PNG', optimize=True); return b.getvalue()

hlsl = read(src + '/SMAA.hlsl')
licence = hlsl[:hlsl.index('*/') + 2]
code = re.sub(r'/\*.*?\*/', '', hlsl[len(licence):], flags=re.S)
code = re.sub(r'//[^\n]*', '', code)
lines = [l.rstrip() for l in code.split('\n')]
code = '\n'.join(l for l in lines if l.strip()) + '\n'
assert code.isascii() and '"' not in code and '\\' not in code

aw, ah, area = tex_bytes(src + '/Textures/AreaTex.h', 'AREATEX')
sw, sh, search = tex_bytes(src + '/Textures/SearchTex.h', 'SEARCHTEX')
assert len(area) == aw * ah * 2 and len(search) == sw * sh
rg = Image.frombytes('LA', (aw, ah), area)                 # R -> grey, G -> alpha
area_png, search_png = png(rg), png(Image.frombytes('L', (sw, sh), search))
chk = Image.open(io.BytesIO(area_png)); assert chk.mode == 'LA' and chk.tobytes() == area

def carray(name, data):
    rows = [', '.join('%d' % b for b in data[i:i + 32]) for i in range(0, len(data), 32)]
    return 'static const unsigned char %s[%d] = {\n%s\n};\n' % (name, len(data), ',\n'.join(rows))

with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('/* smaa.h - SMAA by Jorge Jimenez et al. (https://www.iryoku.com/smaa/, https://github.com/iryoku/smaa), MIT licence below.\n')
    f.write(' * GENERATED by tools/smaa_embed.py: SMAA.hlsl without its comments, AreaTex / SearchTex as PNG. Do not edit. */\n')
    f.write(licence + '\n')
    f.write('#define SMAA_AREA_W %d\n#define SMAA_AREA_H %d\n#define SMAA_SEARCH_W %d\n#define SMAA_SEARCH_H %d\n' % (aw, ah, sw, sh))
    f.write('static const char k_smaa_src[] =\n')
    for l in code.split('\n')[:-1]:
        f.write('    "%s\\n"\n' % l)
    f.write('    ;\n')
    f.write(carray('k_smaa_area_png', area_png))
    f.write(carray('k_smaa_search_png', search_png))
print('%s: shader %d B, AreaTex png %d B, SearchTex png %d B' % (out, len(code), len(area_png), len(search_png)))
